const $=id=>document.getElementById(id);const n=id=>Number($(id)?.value||0)||0;const money=x=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(x)||0);
function toggleNav(){document.getElementById("navLinks").classList.toggle("open")}
function addComp(data={}){const tr=document.createElement("tr");tr.innerHTML=`<td><input class="c-address" value="${data.address||""}"></td><td><input class="c-miles" type="number" step=".1" value="${data.miles??""}"></td><td><input class="c-price" type="number" value="${data.price??""}"></td><td><input class="c-sqft" type="number" value="${data.sqft??""}"></td><td><input class="c-beds" type="number" value="${data.beds??""}"></td><td><input class="c-baths" type="number" step=".5" value="${data.baths??""}"></td><td class="ppsf">$0</td><td><input class="c-source" value="${data.source||""}"></td>`;document.querySelector("#compTable tbody").appendChild(tr);tr.querySelectorAll("input").forEach(x=>x.addEventListener("input",calculateValuation));calculateValuation()}
function calculateValuation(){const rows=[...document.querySelectorAll("#compTable tbody tr")];const comps=rows.map(r=>{const price=Number(r.querySelector(".c-price").value)||0,sqft=Number(r.querySelector(".c-sqft").value)||0,miles=Number(r.querySelector(".c-miles").value)||999; r.querySelector(".ppsf").textContent=sqft?money(price/sqft):"—";return{price,sqft,miles}}).filter(x=>x.price);if(!comps.length){$("valuationOutput").innerHTML="Add sold comps/listings with actual mileage to run the comparison.";return}const weighted=comps.reduce((s,c)=>s+c.price/(1+Math.max(c.miles,0)),0)/comps.reduce((s,c)=>s+1/(1+Math.max(c.miles,0)),0);$("valuationOutput").innerHTML=`<b>Distance-weighted reference:</b> ${money(weighted)}<br><span class="muted">This is a comparison aid, not an appraisal. Give closer, truly comparable sold properties more weight and review condition, size and bed/bath differences.</span>`}
function calculateUW(){const arv=n("uwArv"),purchase=n("purchase"),rehab=n("rehab"),closing=n("closing"),holding=n("holding"),selling=n("selling"),finance=n("finance"),cont=n("contingency"),equity=n("equity"),profit=n("profit"),ltc=n("ltc")/100,ltv=n("ltv")/100;const total=purchase+rehab+closing+holding+selling+finance+cont;const mao=Math.max(arv-rehab-closing-holding-selling-finance-cont-profit,0);const ltcCap=Math.max((purchase+rehab+closing+holding+finance+cont)*ltc,0);const ltvCap=arv*ltv;const lenderMax=Math.min(ltcCap,ltvCap);const cashNeed=Math.max(total-lenderMax,0);const profitCalc=arv-total;document.querySelector("#totalCost").textContent=money(total);document.querySelector("#mao").textContent=money(mao);document.querySelector("#allInPct").textContent=arv?(total/arv*100).toFixed(1)+"%":"0%";document.querySelector("#ltcCap").textContent=money(ltcCap);document.querySelector("#ltvCap").textContent=money(ltvCap);document.querySelector("#lenderMax").textContent=money(lenderMax);document.querySelector("#cashNeed").textContent=money(cashNeed);document.querySelector("#profitCalc").textContent=money(profitCalc);$("uwStatus").innerHTML=`<b>Lender view:</b> illustrative max loan is constrained by the lower of LTC (${(ltc*100).toFixed(1)}%) and ARV LTV (${(ltv*100).toFixed(1)}%).<br><br><b>Investor view:</b> MAO is ARV less all modeled costs and desired profit. These are planning calculations, not lender approval.`;
}
addComp({address:"462 Plane St, Weatherly, PA",price:350000,source:"Homes.com sold — verify mileage"});
addComp({address:"1020 E Main St, Weatherly, PA",price:284000,sqft:1248,source:"Homes.com sold — verify mileage"});
addComp({address:"146 W Main St, Weatherly, PA",price:208000,sqft:1612,source:"Homes.com sold — verify mileage"});
calculateUW();
